### PR TITLE
REST schema config for Phone number field.

### LINKED ISSUE #69: REST API - is not accepting phone number
#REST API - is not accepting phone number

**Issue Description**

1) We tried passing e.164 formatted number.
```
{
"acf": {
"user_mobile": "+910000000000"
}
}
```

2) Also tried the formatted array.
```
{
"acf": {
"user_mobile": {
"carrier": "XYZ",
"country": "India",
"e164": "+91000000000",
"international": "+91 00000 00000",
"location": "India",
"national": "000000 00000",
"number": "000000 00000",
"rfc3966": "tel:+91-00000-00000",
"timezone": [
"Asia/Calcutta"
],
"uri": "tel:+910000000000"
}
}
}
```

3) Event tried db entry format:
```
{
"acf": {
"user_mobile": {
"number": "+91 00 0000 0000",
"country": "in"
}
}
}

===
ERROR for 1:::
It simply overrides to an empty value.
```
{
acf": {
"user_mobile": []
}
}
```

ERROR for 2 & 3:::
```
{
"code": "rest_invalid_param",
"message": "Invalid parameter(s): acf",
"data": {
"status": 400,
"params": {
"acf": "acf[user_mobile] is not of type string,null."
},
"details": {
"acf": {
"code": "rest_invalid_type",
"message": "acf[user_mobile] is not of type string,null.",
"data": {
"param": "acf[user_mobile]"
}
}
}
}
}
```

**THIS IS A REST API ISSUE.**
---
When we pass the REST API value as such...

```
curl --location 'https://wp.host/wp-json/wp/v2/users/4' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx==' \
--data '{
    "acf": {
        "user_mobile": {"number":"+91 00 0000 0000","country":"in"}
    }
}'

```

That is the URL from Postman where is --data is the 3) version of the input. But inputs are giving issues. 

https://capture.dropbox.com/eDrI1M3KE8BYCOXv


All other ACF fields are saving and working without error.
Only when the field type is "ACF Phone Number" those are the ones that are giving and error or saving empty.

### PR DESCRIPTION
**Pull request by joostdekeijzer**
Field needs a modified schema config (it's an object, not a string).

Fixes #69

### CODE REVIEW

**Comment by Log1x** [comment]
Hi, thanks for the PR.

Do you mind updating the code style to match the rest of the project as well as adding a docblock?

**Comment by joostdekeijzer** [comment]
Hi,

Updated to the project coding style (as far as I could see at least ;) and added docblock.

**Comment by joostdekeijzer** [comment]
Is it possible to release a new version with this fix included?

**Comment by Log1x** [comment]
done! sorry about that

**Pull request merged**
